spring.application.name=api

management.endpoints.web.exposure.include=health

spring.datasource.url=jdbc:${DB_TYPE}://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

cors.mappings[0].path=/api/v1/**
cors.mappings[0].allowed-origins[0]=http://localhost:5173
cors.mappings[0].allowed-methods[0]=GET
cors.mappings[0].allowed-methods[1]=POST
cors.mappings[0].allowed-methods[2]=PUT
cors.mappings[0].allowed-methods[3]=DELETE
cors.mappings[0].allowed-methods[4]=PATCH
cors.mappings[0].allowed-headers[0]=*
cors.mappings[0].allow-credentials=true
cors.mappings[0].max-age=3600
